package com.nextint.learncrypto.app.util

const val SESSION = "session"
const val KEY_ONBOARD = "on_boarding"
const val BASE_URL = "https://api.coinpaprika.com/v1/"
const val ID_COIN_CONSTANT = "ID_COIN"
const val ID_TEAM_CONSTANT = "ID_TEAM"
const val ID_EXCHANGE_CONSTANT = "ID_EXC"
const val STRING_TAG_ID_CONSTANT = "ID_TAG"
const val MODEL_PARCEL_TAG = "TAG_PARCELABLE"
const val MODEL_PARCEL_MARKET_BY_ID = "MARKET_PARCELABLE"
const val BUNDLE_WEB_URL = "URL"
const val STRING_URL_AVATAR_APE ="https://images.unsplash.com/photo-1557978556-b33c86cbeeae?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=465&q=80"
const val KEY_BUNDLE_MODEL_DIALOG = "MODEL_DIALOG"
const val KEY_BUNDLE_DATA = "MODEL_DATA"
const val TAG_DIALOG = "TAG"
const val TAG_BOTTOM_SHEET_DIALOG = "BOTTOM_SHEET_DIALOG_TAG"
const val STRING_NOTIFICATION_CHANNELNAME = "CHANNEL_NAME"
const val STRING_NOTIFICATION_CHANNELID = "CHANNEL_ID"
const val STRING_NOTIFICATION_ID = "NOTIFICATION_ID"
const val STRING_NOTIFICATION_STATE = "NOTIFICATION_STATE"